name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.11', '3.10', '3.9', '3.8']
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        pip install cupy-cuda12x
        pip install pydub
        pip install soundfile
        pip install mutagen
        pip install logging
    - name: Install package
      run: |
        pip install .
    - name: Run tests
      run: |
        python -m unittest discover -s fat_llama/tests
    id: tests
